### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [ryanveroniwooff/wooff1#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by ryanveroniwooff** [comment]
Hello,

Thank you for pointing out that issue! 

I found out what the "mobile meta tag" does and after a little hunting went ahead and implemented it, like so:

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```
I added this code to the application.html.erb file, that is the only place I need it, right? 

If there are any other issues I would love to get working on those! Thanks again.

**Comment by ryanveroniwooff** [comment]
Should I ignore the "width=device-width" ?

After a little more reading I realize this affects the user in landscape mode.

**Comment by BillyMassey** [comment]
Your initial section looks great.  I’d use the first result you had, only include it in application.html.erb, then commit & deploy it out to heroku again.
